version: '3.8'

services:
  mysql:
    image: mysql:8.0.38
    container_name: mysql_cp
    restart: always
    ports:
      - "43306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: cache_practice
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  redis:
    image: redis:7.2.1-alpine
    container_name: redis_cp
    restart: always
    ports:
      - "26379:6379"
    networks:
      - backend

  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter_cp
    command:
      # 컨테이너 내부 Redis 포트(6379)로 연결
      - '--redis.addr=redis:6379'
    ports:
      - "9121:9121"
    depends_on:
      - redis
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
    driver: local
