spring:
  profiles:
    active: local
  application:
    name: cache-test

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC # JPA ???? UTC? ??

---
spring:
  config:
    activate:
      on-profile: local

  datasource:

    url: jdbc:mysql://localhost:23306/cache_practice?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: admin1234

  data:
    redis:
      host: localhost
      port: 26379

  management:
    endpoints:
      web:
        exposure:
          include: health,info,prometheus
    endpoint:
      prometheus:
        enabled: true


---

spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://mysql:23306/cache_practice?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: admin1234

  data:
    redis:
      host: redis
      port: 26379
